/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import * as utils from "../internal/utils";
import * as components from "../models/components";
import { Catalog } from "./catalog";
import { Inference } from "./inference";
import { Search } from "./search";
import axios from "axios";
import { AxiosInstance } from "axios";

/**
 * Contains the list of servers available to the SDK
 */
export const ServerList = ["https://api.venari.ai"] as const;

/**
 * The available configuration options for the SDK
 */
export type SDKProps = {
    apiKey?: string;

    /**
     * Allows overriding the default axios client used by the SDK
     */
    defaultClient?: AxiosInstance;

    /**
     * Allows overriding the default server used by the SDK
     */
    serverIdx?: number;

    /**
     * Allows overriding the default server URL used by the SDK
     */
    serverURL?: string;
    /**
     * Allows overriding the default retry config used by the SDK
     */
    retryConfig?: utils.RetryConfig;
};

export class SDKConfiguration {
    defaultClient: AxiosInstance;
    security?: components.Security | (() => Promise<components.Security>);
    serverURL: string;
    serverDefaults: any;
    language = "typescript";
    openapiDocVersion = "1.0.0";
    sdkVersion = "0.0.1";
    genVersion = "2.237.3";
    userAgent = "speakeasy-sdk/typescript 0.0.1 2.237.3 1.0.0 venari-ai";
    retryConfig?: utils.RetryConfig;
    public constructor(init?: Partial<SDKConfiguration>) {
        Object.assign(this, init);
    }
}

/**
 * Venari AI Sneaker Inference API: The Venari AI Sneaker Inference API allows you to submit images, either as single requests or in batches, and receive inference results specifying which sneaker is present in the picture. The API also supports asynchronous requests using webhooks for improved flexibility and responsiveness.
 *
 * @remarks
 *
 * ## Base URL
 *
 * The base URL for accessing the Venari AI Sneaker Inference API is `https://api.venari.ai/`.
 *
 * ## Authentication
 *
 * To use the API, you need to include an API key in the request headers:
 *
 * ```plaintext
 * X-Api-Key: YOUR_API_KEY
 * ```
 */
export class VenariAI {
    public inference: Inference;
    public search: Search;
    public catalog: Catalog;

    private sdkConfiguration: SDKConfiguration;

    constructor(props?: SDKProps) {
        let serverURL = props?.serverURL;
        const serverIdx = props?.serverIdx ?? 0;

        if (!serverURL) {
            serverURL = ServerList[serverIdx];
        }

        const defaultClient = props?.defaultClient ?? axios.create();
        this.sdkConfiguration = new SDKConfiguration({
            defaultClient: defaultClient,
            security: new components.Security({ apiKey: props?.apiKey }),

            serverURL: serverURL,
            retryConfig: props?.retryConfig,
        });

        this.inference = new Inference(this.sdkConfiguration);
        this.search = new Search(this.sdkConfiguration);
        this.catalog = new Catalog(this.sdkConfiguration);
    }
}
