/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import * as components from "../../models/components";
import { AxiosResponse } from "axios";

export class CatalogSearchRequest extends SpeakeasyBase {
    /**
     * The text query.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=query" })
    query: string;

    /**
     * The maximum number of results to return.
     */
    @SpeakeasyMetadata({ data: "queryParam, style=form;explode=true;name=limit" })
    limit?: number;
}

export class CatalogSearchResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * Search results
     */
    @SpeakeasyMetadata({ elemType: components.SearchResult })
    classes?: components.SearchResult[];
}
