/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { AxiosResponse } from "axios";
import { Expose } from "class-transformer";

/**
 * Successfully added item to catalog
 */
export class CatalogItemAddResponseBody extends SpeakeasyBase {
    /**
     * The status of the the operation.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status?: string;
}

export class CatalogItemAddResponse extends SpeakeasyBase {
    /**
     * HTTP response content type for this operation
     */
    @SpeakeasyMetadata()
    contentType: string;

    /**
     * HTTP response status code for this operation
     */
    @SpeakeasyMetadata()
    statusCode: number;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @SpeakeasyMetadata()
    rawResponse: AxiosResponse;

    /**
     * Successfully added item to catalog
     */
    @SpeakeasyMetadata()
    object?: CatalogItemAddResponseBody;
}
