/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose, Type } from "class-transformer";

export enum Status {
    Active = "active",
    Inactive = "inactive",
    Deleted = "deleted",
}

export class Images extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url: string;

    @SpeakeasyMetadata()
    @Expose({ name: "alt_text" })
    altText?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "width" })
    width?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "height" })
    height?: number;
}

export enum TypeT {
    Barcode = "barcode",
    Gtin = "gtin",
    Ean = "ean",
}

export class ProductCode extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "type" })
    type?: TypeT;

    @SpeakeasyMetadata()
    @Expose({ name: "value" })
    value?: string;
}

export class Variants extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "sku" })
    sku: string;

    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "price" })
    price: number;

    @SpeakeasyMetadata()
    @Expose({ name: "compare_at_price" })
    compareAtPrice?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "product_code" })
    @Type(() => ProductCode)
    productCode?: ProductCode;

    @SpeakeasyMetadata()
    @Expose({ name: "position" })
    position?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "inventory_quantity" })
    inventoryQuantity?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "size" })
    size?: string;
}

export class CatalogItem extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "external_id" })
    externalId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title: string;

    @SpeakeasyMetadata()
    @Expose({ name: "product_type" })
    productType: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: Status;

    @SpeakeasyMetadata()
    @Expose({ name: "mpn" })
    mpn?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "brand" })
    brand?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "category" })
    category?: string[];

    @SpeakeasyMetadata()
    @Expose({ name: "description" })
    description?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "product_url" })
    productUrl: string;

    @SpeakeasyMetadata()
    @Expose({ name: "tags" })
    tags?: string[];

    @SpeakeasyMetadata({ elemType: Images })
    @Expose({ name: "images" })
    @Type(() => Images)
    images: Images[];

    @SpeakeasyMetadata({ elemType: Variants })
    @Expose({ name: "variants" })
    @Type(() => Variants)
    variants: Variants[];
}
