/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose, Type } from "class-transformer";

export class ColorWeights extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "color_name" })
    colorName: string;

    @SpeakeasyMetadata()
    @Expose({ name: "weight" })
    weight: number;
}

export class Upcs extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "size" })
    size: number;

    @SpeakeasyMetadata()
    @Expose({ name: "upc" })
    upc: string;
}

export class Product extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "product_id" })
    productId: number;

    @SpeakeasyMetadata()
    @Expose({ name: "style_id" })
    styleId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "product_title" })
    productTitle: string;

    @SpeakeasyMetadata()
    @Expose({ name: "brand_name" })
    brandName: string;

    @SpeakeasyMetadata()
    @Expose({ name: "silhouette" })
    silhouette?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "gender" })
    gender: string;

    @SpeakeasyMetadata()
    @Expose({ name: "age_group" })
    ageGroup: string;

    @SpeakeasyMetadata()
    @Expose({ name: "shaft_style" })
    shaftStyle?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "upper_material" })
    upperMaterial?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "release_date" })
    releaseDate?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "colorway" })
    colorway?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "designer" })
    designer?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "cat1" })
    cat1: string;

    @SpeakeasyMetadata()
    @Expose({ name: "cat2" })
    cat2?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "cat3" })
    cat3?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "cat4" })
    cat4?: string;

    @SpeakeasyMetadata({ elemType: ColorWeights })
    @Expose({ name: "color_weights" })
    @Type(() => ColorWeights)
    colorWeights: ColorWeights[];

    @SpeakeasyMetadata({ elemType: Upcs })
    @Expose({ name: "upcs" })
    @Type(() => Upcs)
    upcs: Upcs[];

    @SpeakeasyMetadata()
    @Expose({ name: "image" })
    image: string;
}
