/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose, Type } from "class-transformer";

export class SearchSimilarByItemResultsProducts extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "rank" })
    rank: number;

    @SpeakeasyMetadata()
    @Expose({ name: "brand" })
    brand?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "image" })
    image: string;

    @SpeakeasyMetadata()
    @Expose({ name: "price" })
    price: number;

    @SpeakeasyMetadata()
    @Expose({ name: "title" })
    title: string;

    @SpeakeasyMetadata()
    @Expose({ name: "status" })
    status: string;

    @SpeakeasyMetadata()
    @Expose({ name: "external_id" })
    externalId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "product_url" })
    productUrl?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "product_type" })
    productType: string;

    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    @SpeakeasyMetadata()
    @Expose({ name: "score" })
    score?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "alt_text" })
    altText?: string;
}

export class Products extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "results" })
    results: number;

    @SpeakeasyMetadata({ elemType: SearchSimilarByItemResultsProducts })
    @Expose({ name: "products" })
    @Type(() => SearchSimilarByItemResultsProducts)
    products: SearchSimilarByItemResultsProducts[];
}

export class SearchSimilarByItemResults extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "products" })
    @Type(() => Products)
    products: Products;
}
