/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

export class SearchResult extends SpeakeasyBase {
    @SpeakeasyMetadata()
    @Expose({ name: "id" })
    id: string;

    @SpeakeasyMetadata()
    @Expose({ name: "style_id" })
    styleId: string;

    @SpeakeasyMetadata()
    @Expose({ name: "product_title" })
    productTitle: string;

    @SpeakeasyMetadata()
    @Expose({ name: "brand_name" })
    brandName: string;

    @SpeakeasyMetadata()
    @Expose({ name: "age_group" })
    ageGroup?: string;

    @SpeakeasyMetadata()
    @Expose({ name: "release_year" })
    releaseYear?: number;

    @SpeakeasyMetadata()
    @Expose({ name: "image" })
    image: string;
}
