/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

/**
 * Payload for similar item search.
 */
export class SimilarItemPayload extends SpeakeasyBase {
    /**
     * The external id of the item to search for.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "external_id" })
    externalId: string;

    /**
     * The minimum score of the results to return.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "min_score" })
    minScore?: number;
}
