/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

export class SneakersIdAsyncRequest extends SpeakeasyBase {
    /**
     * User-defined flat object to be returned in the response.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "custom" })
    custom?: Record<string, any>;

    /**
     * The confidence threshold value.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "confidence_threshold" })
    confidenceThreshold?: number;

    /**
     * A boolean flag for restrictive mode.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "restrictive_mode" })
    restrictiveMode?: boolean;

    /**
     * The sneaker's image URL.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url: string;

    /**
     * The URL to which the webhook will be delivered once the identification process is completed.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "postback_url" })
    postbackUrl: string;
}
