/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

export class SneakersIdRequest extends SpeakeasyBase {
    /**
     * User-defined flat object to be returned in the response.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "custom" })
    custom?: Record<string, any>;

    /**
     * The confidence threshold value.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "confidence_threshold" })
    confidenceThreshold?: number;

    /**
     * A boolean flag for restrictive mode.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "restrictive_mode" })
    restrictiveMode?: boolean;

    /**
     * The sneaker's image URL.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "url" })
    url: string;

    /**
     * Whether to include sneaker variants.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "variants" })
    variants?: boolean;
}
