/*
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

import { SpeakeasyBase, SpeakeasyMetadata } from "../../internal/utils";
import { Expose } from "class-transformer";

export class SneakersIdBatchAsyncRequest extends SpeakeasyBase {
    /**
     * User-defined flat object to be returned in the response.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "custom" })
    custom?: Record<string, any>;

    /**
     * The confidence threshold value.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "confidence_threshold" })
    confidenceThreshold?: number;

    /**
     * A boolean flag for restrictive mode.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "restrictive_mode" })
    restrictiveMode?: boolean;

    /**
     * The URL to which the webhook will be delivered once the identification process is completed.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "postback_url" })
    postbackUrl: string;

    /**
     * The sneaker's array of image URLs. Specify a maximum of 32 urls.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "urls" })
    urls: string[];

    /**
     * The sneaker's listing id to be asociated with the array of images.
     */
    @SpeakeasyMetadata()
    @Expose({ name: "listing_id" })
    listingId: string;
}
